// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hptdavnevtdowxiqdvvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFheW5vdm5nZmR5ZnZtdXV5b21vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMjI1NjYsImV4cCI6MjA2ODY5ODU2Nn0.9HVbay-hjCB0LQeGTJSMKhy5RJMPAjTr0_NdsBMFV5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});